# Generated by Django 3.0.5 on 2021-10-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMarkitDB', '0002_auto_20211001_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_avail',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
